export const modules = [
    '',
    "Company",
    "Platform Services",
    "General Ledger",
    "Cash Management",
    "Accounts Payable",
    "Accounts Receivable",
    "Budgets",
    "Order Entry",
    "Purchasing",
    "Revenue Recognition - Standard",
    "Projects",
    "Construction",
    "Contracts",
    "Expense Recognition",
    "Dashboards",
    "Global Consolidation",
    "Domestic Consolidation",
    "Revenue Recognition - Advance",
    "Inventory Control",
    "Reports",
    "Taxes",
    "Time & Expense",
    "Prepaid Expense Amortization",
    "Fixed Assets",
    "Interactive Custom Report Writer (ICRW)",
]